In [1]:
import os

import chromadb
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer

# Load the TMDB Movies dataset
movies = pd.read_csv('../Data/tmdb_5000_movies.csv')
credits = pd.read_csv('../Data/tmdb_5000_credits.csv')

# Let's take a peek at what we're working with
print(f"Total movies: {len(movies)}")
movies[['title', 'overview', 'genres', 'release_date']].head(2)

Total movies: 4803

,title,overview,genres,release_date
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",2009-12-10
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",2007-05-19

In [2]:
import json


# Extract genres from JSON string
def extract_genres(genres_json):
    try:
        genres_list = json.loads(genres_json.replace("'", '"'))
        return [genre['name'] for genre in genres_list]
    except:
        return []

# Apply extraction
movies['genres_list'] = movies['genres'].apply(extract_genres)

# Now create rich document representations with movie descriptions
def create_movie_documents(movies):
    """Create rich document representations of movies with descriptions."""
    documents = []
    
    for _, movie in movies.iterrows():
        movie_id = movie['id']
        title = movie['title']
        overview = movie['overview']
        
        # Extract year from release date if present
        year = ""
        if pd.notna(movie['release_date']) and len(movie['release_date']) >= 4:
            year = movie['release_date'][:4]  # Just the year
        
        genres = movie['genres_list']
        
        # Create document text - this will be embedded
        doc = f"Movie: {title}\n"
        if year:
            doc += f"Year: {year}\n"
        if genres and len(genres) > 0:
            doc += f"Genres: {', '.join(genres)}\n"
        if overview and pd.notna(overview):
            doc += f"Overview: {overview}\n"
        
        documents.append({
            'id': str(movie_id),
            'content': doc,
            'metadata': {
                'title': title,
                'year': year,
                'genres': "|".join(genres),
                'overview': overview if pd.notna(overview) else ""
            }
        })
    
    return documents

# Create our document collection
movie_documents = create_movie_documents(movies)
print(f"Created {len(movie_documents)} movie documents")
print(f"Sample document:")
print(movie_documents[1]['content'])

Created 4803 movie documents
Sample document:
Movie: Pirates of the Caribbean: At World's End
Year: 2007
Genres: Adventure, Fantasy, Action
Overview: Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.

In [3]:
model = SentenceTransformer('all-MiniLM-L6-v2')

chroma_client = chromadb.Client()

# Re-running this cell should reset the collection instead of erroring on
# "Collection already exists" (the in-memory client persists across reruns
# within the same kernel session).
try:
    chroma_client.delete_collection(name="my_movies_index")
except Exception:
    pass

collection = chroma_client.create_collection(name = "my_movies_index")

batch_size = 1000
for i in range(0, len(movie_documents), batch_size):
    batch = movie_documents[i:i + batch_size]
    ids = [doc['id'] for doc in batch]
    contents = [doc['content'] for doc in batch]
    metadatas = [doc['metadata'] for doc in batch]
    
    # Create embeddings for the batch
    embeddings = model.encode(contents, show_progress_bar=True)
    
    # Add to Chroma collection
    collection.add(
        ids=ids,
        documents=contents,
        metadatas=metadatas,
        embeddings=embeddings.tolist()  # Convert to list for JSON serialization
    )
    
print(f"Added {collection.count()} documents to the Chroma collection.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

Batches:   0%|          | 0/26 [00:00<?, ?it/s]

Added 4803 documents to the Chroma collection.

In [4]:
test_query = "A movie about mission which seems to impossible"
query_embedding = model.encode(test_query).tolist()

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=5
)




for i , (doc, metadata) in enumerate(zip(results['documents'][0], results['metadatas'][0])):
    print(f"Result {i+1}:")
    print(f"Document: {doc}")
    print(f"Metadata: {metadata}")
    print("\n")

Result 1:
Document: Movie: Mission: Impossible II
Year: 2000
Genres: Adventure, Action, Thriller
Overview: With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.

Metadata: {'year': '2000', 'overview': 'With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.', 'title': 'Mission: Impossible II', 'genres': 'Adventure|Action|Thriller'}


Result 2:
Document: Movie: Mission: Impossible - Rogue Nation
Year: 2015
Genres: Action, Adventure, Thriller
Overview: Ethan and team take on their most impossible mission yet, eradicating the Syndicate - an International rogue organization as highly skilled as they are, committed to destroying the IMF.

Metadata: {'title': 'Mission: Impossible - Rogue Nation', 'genres': 'Action|Adventure|Thriller', 'year': '2015', 'overview': 'Ethan and team take on their most impossible mission yet, eradicating the Syndicate - an International rogue organization as highly skilled as they are, committed to destroying the IMF.'}


Result 3:
Document: Movie: Mission: Impossible - Ghost Protocol
Year: 2011
Genres: Action, Thriller, Adventure
Overview: In the 4th installment of the Mission Impossible series, Ethan Hunt (Cruise) and his team are racing against time to track down a dangerous terrorist named Hendricks (Nyqvist), who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.

Metadata: {'overview': 'In the 4th installment of the Mission Impossible series, Ethan Hunt (Cruise) and his team are racing against time to track down a dangerous terrorist named Hendricks (Nyqvist), who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.', 'year': '2011', 'title': 'Mission: Impossible - Ghost Protocol', 'genres': 'Action|Thriller|Adventure'}


Result 4:
Document: Movie: Mission: Impossible
Year: 1996
Genres: Adventure, Action, Thriller
Overview: When Ethan Hunt, the leader of a crack espionage team whose perilous operation has gone awry with no explanation, discovers that a mole has penetrated the CIA, he's surprised to learn that he's the No. 1 suspect. To clear his name, Hunt now must ferret out the real double agent and, in the process, even the score.

Metadata: {'overview': "When Ethan Hunt, the leader of a crack espionage team whose perilous operation has gone awry with no explanation, discovers that a mole has penetrated the CIA, he's surprised to learn that he's the No. 1 suspect. To clear his name, Hunt now must ferret out the real double agent and, in the process, even the score.", 'title': 'Mission: Impossible', 'year': '1996', 'genres': 'Adventure|Action|Thriller'}


Result 5:
Document: Movie: Mission: Impossible III
Year: 2006
Genres: Adventure, Action, Thriller
Overview: Retired from active duty to train new IMF agents, Ethan Hunt is called back into action to confront sadistic arms dealer, Owen Davian. Hunt must try to protect his girlfriend while working with his new team to complete the mission.

Metadata: {'genres': 'Adventure|Action|Thriller', 'title': 'Mission: Impossible III', 'overview': 'Retired from active duty to train new IMF agents, Ethan Hunt is called back into action to confront sadistic arms dealer, Owen Davian. Hunt must try to protect his girlfriend while working with his new team to complete the mission.', 'year': '2006'}

In [5]:
def query_expansion(query):
    """Expand the query to improve retrieval."""
    # Simple rule-based expansions
    expansions = [
        query,  # Original query
        f"Movies similar to {query}",
        f"Plot description: {query}",
        f"Movie themes and content about {query}"
    ]
    return expansions


query_expansion(test_query)

['A movie about mission which seems to impossible',
 'Movies similar to A movie about mission which seems to impossible',
 'Plot description: A movie about mission which seems to impossible',
 'Movie themes and content about A movie about mission which seems to impossible']

In [6]:
def retrieve_movie_info(query, n_results=5):
    """Retrieve relevant movie information for a query."""
    # Expand query for better recall
    expanded_queries = query_expansion(query)
    
    all_results = []
    for expanded_query in expanded_queries:
        # Generate embedding for the query
        query_embedding = model.encode(expanded_query).tolist()
        
        # Retrieve relevant documents
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results
        )
        
        # Add to results list
        for doc, metadata, id in zip(results['documents'][0], 
                                    results['metadatas'][0],
                                    results['ids'][0]):
            all_results.append({
                'id': id,
                'document': doc,
                'metadata': metadata,
                'query': expanded_query
            })
    
    # Remove duplicates (same movie ID)
    unique_results = {}
    for result in all_results:
        if result['id'] not in unique_results:
            unique_results[result['id']] = result
    
    return list(unique_results.values())

In [7]:
# Quick sanity check of retrieval before wiring up generation
sample_results = retrieve_movie_info(test_query, n_results=3)
for r in sample_results:
    print(r['metadata']['title'])

Mission: Impossible II
Mission: Impossible - Rogue Nation
Mission: Impossible - Ghost Protocol
Mission: Impossible
Mission to Mars

In [8]:
# In a terminal:
# ollama serve
# ollama pull llama3.2

In [9]:
import ollama
from pydantic import BaseModel, Field, ValidationError

OLLAMA_MODEL = "gemma3:4b"  # must match what you pulled with `ollama pull`

class Content(BaseModel):
    title: str = Field(..., description="title of the movie")
    why_picked: str = Field(..., description="why did you pick it, in ONE short sentence (max ~20 words)")

class ContentList(BaseModel):
    recommendations: list[Content]

def generate_rag_response(query, context, model_name=OLLAMA_MODEL, max_retries=2):
    # Format the prompt with retrieved context
    prompt = f"""
    You are a knowledgeable movie recommendation system with deep understanding of film plots, themes, and content. 
    Use the following retrieved information about movies to answer the user's question.
    
    User Query: {query}
    
    Retrieved Movie Information:
    {context}
    
    Based on this information, provide a helpful response to the user's query.
    If the user is asking about themes, plot elements, or specific content, use the movie overviews to provide detailed insights.

    If the retrieved information doesn't contain relevant details to answer the question, acknowledge the limitations and provide general movie information or suggestions.

    Keep "why_picked" to ONE short sentence per movie (max ~20 words) — do not write paragraphs, and do not add any text outside the JSON.
    """

    messages = [{"role": "user", "content": prompt}]
    last_error = None

    for attempt in range(max_retries + 1):
        response = ollama.chat(
            model=model_name,
            messages=messages,
            format=ContentList.model_json_schema(),  # ask Ollama to constrain output to this schema
            options={
                "temperature": 0.2,      # small models ramble/loop less at low temperature
                "repeat_penalty": 1.3,   # discourages the "2015} , 2015} , 2015}" style loops
                "num_predict": 2048,     # backstop headroom in case responses run long despite the length instruction
            },
        )
        raw = response["message"]["content"]
        try:
            parsed = ContentList.model_validate_json(raw)
            return parsed.recommendations
        except ValidationError as e:
            last_error = e
            # Feed the error back and ask the model to correct itself
            messages = [
                {"role": "user", "content": prompt},
                {"role": "assistant", "content": raw},
                {"role": "user", "content": f"That response was not valid JSON matching the schema ({e}). Reply again with ONLY the corrected valid JSON — no explanation, no text before or after it."},
            ]

    raise last_error

In [10]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

def rerank_results(query, results, top_k=5):
    """Re-rank results based on relevance to query."""
    # Prepare pairs for re-ranking
    pairs = [(query, result['document']) for result in results]

    # Get scores
    scores = reranker.predict(pairs)

    # Add scores to results
    for i, result in enumerate(results):
        result['rerank_score'] = float(scores[i])

    # Sort by score and take top_k
    reranked_results = sorted(results, key=lambda x: x['rerank_score'], reverse=True)[:top_k]

    return reranked_results

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

In [11]:
def movie_rag_without_rerank(user_query, max_context_docs=5):
    """RAG pipeline using raw retrieval order — no reranking."""
    results = retrieve_movie_info(user_query)
    top_results = results[:max_context_docs]

    context = "\n\n".join([res['document'] for res in top_results])
    response = generate_rag_response(user_query, context)

    return response, top_results


def movie_rag_with_rerank(user_query, max_context_docs=5):
    """RAG pipeline using cross-encoder reranked results."""
    results = retrieve_movie_info(user_query)
    top_results = rerank_results(user_query, results, top_k=max_context_docs)

    context = "\n\n".join([res['document'] for res in top_results])
    response = generate_rag_response(user_query, context)

    return response, top_results

In [12]:
def compare_rerank(query, n_results=5):
    """Show retrieval order before vs. after cross-encoder reranking, as a table."""
    raw_results = retrieve_movie_info(query)

    without_rerank = raw_results[:n_results]
    with_rerank = rerank_results(query, raw_results, top_k=n_results)

    comparison = pd.DataFrame({
        "Rank": range(1, n_results + 1),
        "Without rerank": [r['metadata']['title'] for r in without_rerank],
        "With rerank": [r['metadata']['title'] for r in with_rerank],
        "Rerank score": [round(r['rerank_score'], 3) for r in with_rerank],
    }).set_index("Rank")

    print(f"Query: {query}")
    return comparison

compare_rerank(test_query)

Query: A movie about mission which seems to impossible

,Without rerank,With rerank,Rerank score
Rank,,,
1,Mission: Impossible II,Mission: Impossible II,6.564
2,Mission: Impossible - Rogue Nation,Mission: Impossible,6.298
3,Mission: Impossible - Ghost Protocol,Mission: Impossible - Rogue Nation,5.965
4,Mission: Impossible,Mission: Impossible III,5.911
5,Mission: Impossible III,Mission: Impossible - Ghost Protocol,5.324

In [13]:
from itertools import zip_longest

without_response, without_sources = movie_rag_without_rerank(test_query)
with_response, with_sources = movie_rag_with_rerank(test_query)

without_lines = [f"{rec.title} — {rec.why_picked}" for rec in without_response]
with_lines = [f"{rec.title} — {rec.why_picked}" for rec in with_response]

# The LLM can return a different number of recommendations each run, so pad
# the shorter column instead of assuming equal lengths.
rows = list(zip_longest(without_lines, with_lines, fillvalue=""))

recs = pd.DataFrame(rows, columns=["Without rerank", "With rerank"])
recs.index += 1
recs

,Without rerank,With rerank
1,Mission: Impossible II — This film features a ...,Mission: Impossible II — This film features a ...
2,Mission: Impossible - Rogue Nation — The movie...,Mission: Impossible - Rogue Nation — It presen...
3,"Mission: Impossible – Ghost Protocol”, “why_p...",Mission: Impossible III — Hunt’s mission to pr...
4,"Mission: Impossible III”, “why_picked”: “This...",

In [14]:
def hyde_retrieval(query, n_results=5, model_name=OLLAMA_MODEL, verbose=True):
    """Implement HyDE for better retrieval."""
    # Step 1: Generate a hypothetical document using a local Ollama model
    hyde_prompt = f"""
    You are a movie expert. Generate a detailed description of a movie that would perfectly answer this query: "{query}"
    Include details about plot, themes, genre, and style.
    """

    hyde_response = ollama.chat(
        model=model_name,
        messages=[{"role": "user", "content": hyde_prompt}],
        options={
            "temperature": 0.7,      # HyDE wants a plausible, varied description, not a terse one
            "repeat_penalty": 1.3,
            "num_predict": 512,
        },
    )

    hypothetical_document = hyde_response["message"]["content"]

    if verbose:
        print("=== HyDE hypothetical document ===")
        print(hypothetical_document)
        print("===================================\n")

    # Step 2: Embed this hypothetical document instead of the query
    hyde_embedding = model.encode(hypothetical_document).tolist()

    # Step 3: Use this embedding for retrieval
    results = collection.query(
        query_embeddings=[hyde_embedding],
        n_results=n_results
    )

    # Format results
    formatted_results = []
    for doc, metadata, id in zip(results['documents'][0], 
                                results['metadatas'][0],
                                results['ids'][0]):
        formatted_results.append({
            'id': id,
            'document': doc,
            'metadata': metadata,
            'query': query
        })

    return formatted_results

In [15]:
def movie_hyde_rag_without_rerank(user_query, max_context_docs=5, hyde_results=None):
    """HyDE RAG pipeline using raw retrieval order — no reranking."""
    results = hyde_results if hyde_results is not None else hyde_retrieval(user_query, n_results=15)
    top_results = results[:max_context_docs]

    context = "\n\n".join([res['document'] for res in top_results])
    response = generate_rag_response(user_query, context)

    return response, top_results


def movie_hyde_rag_with_rerank(user_query, max_context_docs=5, hyde_results=None):
    """HyDE RAG pipeline using cross-encoder reranked results."""
    results = hyde_results if hyde_results is not None else hyde_retrieval(user_query, n_results=15)
    top_results = rerank_results(user_query, results, top_k=max_context_docs)

    context = "\n\n".join([res['document'] for res in top_results])
    response = generate_rag_response(user_query, context)

    return response, top_results

In [16]:
# Generate the HyDE hypothetical document once and reuse it for both branches
# below, so the comparison isolates the effect of reranking rather than
# mixing in a different HyDE hallucination each run.
hyde_candidates = hyde_retrieval(test_query, n_results=15)

hwithout_response, hwithout_sources = movie_hyde_rag_without_rerank(test_query, hyde_results=hyde_candidates)
hwith_response, hwith_sources = movie_hyde_rag_with_rerank(test_query, hyde_results=hyde_candidates)

hwithout_lines = [f"{rec.title} — {rec.why_picked}" for rec in hwithout_response]
hwith_lines = [f"{rec.title} — {rec.why_picked}" for rec in hwith_response]

hyde_rows = list(zip_longest(hwithout_lines, hwith_lines, fillvalue=""))

hyde_recs = pd.DataFrame(hyde_rows, columns=["Without rerank", "With rerank"])
hyde_recs.index += 1
hyde_recs

=== HyDE hypothetical document ===
Okay, let’s craft the perfect film for someone asking “A Movie About A Mission That Seems Impossible.” I'm calling it **“Echo Bloom”**.

**Genre:**  Neo-Noir Thriller with elements of Sci-Fi & Psychological Drama – leaning heavily into atmosphere and suspense.


**Logline**: In a rain-soaked, perpetually twilight city built atop the ruins of an ancient underwater civilization, a disgraced ex-marine haunted by his past must infiltrate a clandestine organization manipulating reality itself to rescue his kidnapped daughter before time - *and sanity* - run out.

---

**Plot (Detailed Breakdown):**


The film opens in Veridia – a sprawling metropolis clinging precariously on the cliffs of what was once coastal California, now submerged and transformed into an eerie underwater labyrinth by centuries-old seismic activity.  Veridian society is rigidly stratified: The 'High Tide' elite live within gleaming towers powered by geothermal energy harvested from beneath; while ‘Low Tides’ – predominantly former military personnel and scavengers - dwell in the decaying remnants of old cities, struggling to survive amidst rising tides and corporate control.

Our protagonist, Elias Thorne (played with a weary intensity by Oscar Isaac-esque talent), is one such Low Tide operative. A decorated marine veteran whose unit was tragically lost during an "unexplained" operation ten years prior – he's now haunted by fragmented memories of the event and drowning in debt due to black market dealings within Veridia’s underbelly.

The film kicks off when Elias receives a coded message: his eight-year old daughter, Lyra (a captivating young Saoirse Ronan), has been abducted by “Chronos,” an organization shrouded in secrecy that controls much of the city's technology and infrastructure—and appears to be manipulating localized time distortions within Veridia. Chronos’ goal is revealed through unsettling flashbacks interwoven throughout Elias' investigation: they believe humanity needs "correction" – a systematic resetting of society every few decades, achieved by exploiting temporal anomalies for their benefit.

Elias isn't just driven by parental instinct; he begins to suspect his own memories from the lost operation are key to Chronos’ plan and that *he* was involved in some way—a suspicion fueled by increasingly bizarre occurrences – pockets of time freezing or looping, objects disappearing then reappearing with subtle alterations.

His mission is a layered nightmare:


1. **Infiltration:** Elias must penetrate Veridia's heavily guarded "Chronos Citadel," located deep within the submerged
===================================

,Without rerank,With rerank
1,The Abyss — This film features a seemingly imp...,Tomorrowland — This film features a mission to...
2,Subconscious — It involves a time-traveling in...,Sanctum — The movie depicts a dangerous expedi...
3,The Ruins — A group undertakes an impossible m...,

In [37]:
class Query(BaseModel):
    query: str

class QueryList(BaseModel):
    sub_queries: list[Query]
    
    
def decompose_query(query):
    """Decompose complex query into simpler sub-queries."""
    decompose_prompt = f"""
    Break down this complex movie-related query into 2-3 simpler sub-queries:
    "{query}"
    """
    
    decompose_response =  ollama.chat(
            model=OLLAMA_MODEL,
            messages=[{"role": "user", "content": decompose_prompt}],
            format=QueryList.model_json_schema(),  # ask Ollama to constrain output to this schema
            options={
                "temperature": 0.2,      # small models ramble/loop less at low temperature
                "repeat_penalty": 1.3,   # discourages the "2015} , 2015} , 2015}" style loops
                "num_predict": 2048,     # backstop headroom in case responses run long despite the length instruction
            },
        )

    
    # Parse the response to get sub-queries
    parsed = QueryList.model_validate_json(decompose_response.message.content)
    sub_queries = [q.query.strip() for q in parsed.sub_queries]
        
    return sub_queries

In [38]:
def retrieve_with_decomposition(query, n_results=3):
    """Retrieve using query decomposition for complex queries."""
    print(f"Original query: {query}")
    
    # Step 1: Decompose the query
    sub_queries = decompose_query(query)
    print(f"Decomposed into: {sub_queries}")
    
    # Step 2: Retrieve for each sub-query
    all_results = []
    for sub_query in sub_queries:
        # Get results for this sub-query
        sub_results = retrieve_movie_info(sub_query, n_results=n_results)
        print(f"Retrieved {len(sub_results)} results for: '{sub_query}'")
        all_results.extend(sub_results)
    
    # Step 3: Remove duplicates and sort by relevance
    unique_results = {}
    for result in all_results:
        if result['id'] not in unique_results:
            unique_results[result['id']] = result
    
    return list(unique_results.values())

def movie_decomposition_rag(user_query):
    # Retrieve relevant movie information
    results = retrieve_with_decomposition(user_query, 5)
    
    # Format context from retrieved documents
    context = "\n\n".join([res['document'] for res in results])

    # Generate response
    response = generate_rag_response(user_query, context)
    
    return response, results

In [39]:
complex_query = "I want science fiction movies that deal with time travel but also have strong character development and emotional depth"
decompose_query(complex_query)

['Find all Science Fiction Movies involving Time Travel.',
 'For the identified science fiction movies about time travel, filter for those with strong character development (e.g., complex characters, significant arcs).',
 'Finally, from that filtered list of films, select only those also exhibiting emotional depth – meaning they explore themes related to feelings and relationships.']

In [27]:
decompose_prompt = f"""
Break down this complex movie-related query into 2-3 simpler sub-queries:
"{complex_query}"
"""

decompose_response =  ollama.chat(
        model=OLLAMA_MODEL,
        messages=[{"role": "user", "content": decompose_prompt}],
        format=ContentList.model_json_schema(),  # ask Ollama to constrain output to this schema
        options={
            "temperature": 0.2,      # small models ramble/loop less at low temperature
            "repeat_penalty": 1.3,   # discourages the "2015} , 2015} , 2015}" style loops
            "num_predict": 2048,     # backstop headroom in case responses run long despite the length instruction
        },
    )


# Parse the response to get sub-queries

In [40]:
retrieve_with_decomposition(complex_query, n_results=3)

Original query: I want science fiction movies that deal with time travel but also have strong character development and emotional depth
Decomposed into: ['Find all Science Fiction Movies involving Time Travel.', 'Filter the results from above to include movies with Strong Character Development.']
Retrieved 4 results for: 'Find all Science Fiction Movies involving Time Travel.'
Retrieved 3 results for: 'Filter the results from above to include movies with Strong Character Development.'

[{'id': '14139',
  'document': 'Movie: Timecrimes\nYear: 2007\nGenres: Science Fiction, Thriller\nOverview: A man accidentally gets into a time machine and travels back in time nearly an hour. Finding himself will be the first of a series of disasters of unforeseeable consequences.\n',
  'metadata': {'genres': 'Science Fiction|Thriller',
   'overview': 'A man accidentally gets into a time machine and travels back in time nearly an hour. Finding himself will be the first of a series of disasters of unforeseeable consequences.',
   'year': '2007',
   'title': 'Timecrimes'},
  'query': 'Find all Science Fiction Movies involving Time Travel.'},
 {'id': '2135',
  'document': 'Movie: The Time Machine\nYear: 2002\nGenres: Science Fiction, Adventure, Action\nOverview: Hoping to alter the events of the past, a 19th century inventor instead travels 800,000 years into the future, where he finds humankind divided into two warring races.\n',
  'metadata': {'title': 'The Time Machine',
   'overview': 'Hoping to alter the events of the past, a 19th century inventor instead travels 800,000 years into the future, where he finds humankind divided into two warring races.',
   'year': '2002',
   'genres': 'Science Fiction|Adventure|Action'},
  'query': 'Find all Science Fiction Movies involving Time Travel.'},
 {'id': '227719',
  'document': 'Movie: Project Almanac\nYear: 2015\nGenres: Science Fiction, Thriller\nOverview: A group of teens discover secret plans of a time machine, and construct one. However, things start to get out of control.\n',
  'metadata': {'overview': 'A group of teens discover secret plans of a time machine, and construct one. However, things start to get out of control.',
   'genres': 'Science Fiction|Thriller',
   'year': '2015',
   'title': 'Project Almanac'},
  'query': 'Find all Science Fiction Movies involving Time Travel.'},
 {'id': '122906',
  'document': "Movie: About Time\nYear: 2013\nGenres: Comedy, Drama, Science Fiction\nOverview: The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks.\n",
  'metadata': {'title': 'About Time',
   'genres': 'Comedy|Drama|Science Fiction',
   'overview': "The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks.",
   'year': '2013'},
  'query': 'Movies similar to Find all Science Fiction Movies involving Time Travel.'},
 {'id': '139998',
  'document': 'Movie: Supporting Characters\nYear: 2012\nGenres: Drama, Comedy\nOverview: Two New York film editors balance their personal relationships while reworking a movie in crisis.\n',
  'metadata': {'year': '2012',
   'title': 'Supporting Characters',
   'overview': 'Two New York film editors balance their personal relationships while reworking a movie in crisis.',
   'genres': 'Drama|Comedy'},
  'query': 'Filter the results from above to include movies with Strong Character Development.'},
 {'id': '76726',
  'document': 'Movie: Chronicle\nYear: 2012\nGenres: Science Fiction, Drama, Thriller\nOverview: Three high school students make an incredible discovery, leading to their developing uncanny powers beyond their understanding. As they learn to control their abilities and use them to their advantage, their lives start to spin out of control, and their darker sides begin to take over.\n',
  'metadata': {'genres': 'Science Fiction|Drama|Thriller',
   'title': 'Chronicle',
   'year': '2012',
   'overview': 'Three high school students make an incredible discovery, leading to their developing uncanny powers beyond their understanding. As they learn to control their abilities and use them to their advantage, their lives start to spin out of control, and their darker sides begin to take over.'},
  'query': 'Filter the results from above to include movies with Strong Character Development.'},
 {'id': '14799',
  'document': 'Movie: For Your Consideration\nYear: 2006\nGenres: Comedy, Drama\nOverview: Three actors learn that their respective performances in the film "Home for Purim," a drama set in the mid-1940s American South, are generating award-season buzz.\n',
  'metadata': {'overview': 'Three actors learn that their respective performances in the film "Home for Purim," a drama set in the mid-1940s American South, are generating award-season buzz.',
   'genres': 'Comedy|Drama',
   'title': 'For Your Consideration',
   'year': '2006'},
  'query': 'Filter the results from above to include movies with Strong Character Development.'}]

In [41]:
movie_decomposition_rag(complex_query)

Original query: I want science fiction movies that deal with time travel but also have strong character development and emotional depth
Decomposed into: ['Find all Science Fiction Movies involving Time Travel.', 'For the identified science fiction movies about time travel, filter for those with strong character development.', 'Finally, from that filtered list of films, select only those also exhibiting emotional depth']
Retrieved 8 results for: 'Find all Science Fiction Movies involving Time Travel.'
Retrieved 7 results for: 'For the identified science fiction movies about time travel, filter for those with strong character development.'
Retrieved 10 results for: 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'

([Content(title='About Time', why_picked='This film excels in character development with a poignant story about family relationships using time travel as its core mechanic.'),
  Content(title='Back to the Future Part II', why_picked='It offers engaging plot twists and explores familial dynamics through multiple temporal journeys.” \xa0} , \xa0 { \x80\xa0“title”: “Timecrimes”, \x80\xa0”why_picked”: “This thriller uses time travel to create a complex, character-driven mystery with significant consequences.'),
  Content(title='The Time Machine', why_picked='It presents an epic future scenario and explores human evolution through the lens of extended temporal displacement.” \xa0} , {“title”: “Project Almanac”, ”why_picked”:'),
  Content(title='Back to the Future Part III', why_picked='This installment features a strong emotional core centered around Doc’s romance, alongside time travel adventures.'),
  Content(title='In Time', why_picked="It tackles social inequality and human connection within an intriguing concept of 'time as currency'.")],
 [{'id': '14139',
   'document': 'Movie: Timecrimes\nYear: 2007\nGenres: Science Fiction, Thriller\nOverview: A man accidentally gets into a time machine and travels back in time nearly an hour. Finding himself will be the first of a series of disasters of unforeseeable consequences.\n',
   'metadata': {'title': 'Timecrimes',
    'year': '2007',
    'overview': 'A man accidentally gets into a time machine and travels back in time nearly an hour. Finding himself will be the first of a series of disasters of unforeseeable consequences.',
    'genres': 'Science Fiction|Thriller'},
   'query': 'Find all Science Fiction Movies involving Time Travel.'},
  {'id': '2135',
   'document': 'Movie: The Time Machine\nYear: 2002\nGenres: Science Fiction, Adventure, Action\nOverview: Hoping to alter the events of the past, a 19th century inventor instead travels 800,000 years into the future, where he finds humankind divided into two warring races.\n',
   'metadata': {'year': '2002',
    'title': 'The Time Machine',
    'overview': 'Hoping to alter the events of the past, a 19th century inventor instead travels 800,000 years into the future, where he finds humankind divided into two warring races.',
    'genres': 'Science Fiction|Adventure|Action'},
   'query': 'Find all Science Fiction Movies involving Time Travel.'},
  {'id': '227719',
   'document': 'Movie: Project Almanac\nYear: 2015\nGenres: Science Fiction, Thriller\nOverview: A group of teens discover secret plans of a time machine, and construct one. However, things start to get out of control.\n',
   'metadata': {'year': '2015',
    'title': 'Project Almanac',
    'genres': 'Science Fiction|Thriller',
    'overview': 'A group of teens discover secret plans of a time machine, and construct one. However, things start to get out of control.'},
   'query': 'Find all Science Fiction Movies involving Time Travel.'},
  {'id': '196',
   'document': 'Movie: Back to the Future Part III\nYear: 1990\nGenres: Adventure, Comedy, Family, Science Fiction\nOverview: The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking up Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More problems arise when Doc falls for pretty schoolteacher Clara Clayton, and Marty tangles with Buford Tannen.\n',
   'metadata': {'year': '1990',
    'genres': 'Adventure|Comedy|Family|Science Fiction',
    'overview': 'The final installment of the Back to the Future trilogy finds Marty digging the trusty DeLorean out of a mineshaft and looking up Doc in the Wild West of 1885. But when their time machine breaks down, the travelers are stranded in a land of spurs. More problems arise when Doc falls for pretty schoolteacher Clara Clayton, and Marty tangles with Buford Tannen.',
    'title': 'Back to the Future Part III'},
   'query': 'Find all Science Fiction Movies involving Time Travel.'},
  {'id': '122906',
   'document': "Movie: About Time\nYear: 2013\nGenres: Comedy, Drama, Science Fiction\nOverview: The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks.\n",
   'metadata': {'genres': 'Comedy|Drama|Science Fiction',
    'year': '2013',
    'title': 'About Time',
    'overview': "The night after another unsatisfactory New Year party, Tim's father tells his son that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life – so he decides to make his world a better place... by getting a girlfriend. Sadly, that turns out not to be as easy as he thinks."},
   'query': 'Find all Science Fiction Movies involving Time Travel.'},
  {'id': '165',
   'document': 'Movie: Back to the Future Part II\nYear: 1989\nGenres: Adventure, Comedy, Family, Science Fiction\nOverview: Marty and Doc are at it again in this wacky sequel to the 1985 blockbuster as the time-traveling duo head to 2015 to nip some McFly family woes in the bud. But things go awry thanks to bully Biff Tannen and a pesky sports almanac. In a last-ditch attempt to set things straight, Marty finds himself bound for 1955 and face to face with his teenage parents -- again.\n',
   'metadata': {'overview': 'Marty and Doc are at it again in this wacky sequel to the 1985 blockbuster as the time-traveling duo head to 2015 to nip some McFly family woes in the bud. But things go awry thanks to bully Biff Tannen and a pesky sports almanac. In a last-ditch attempt to set things straight, Marty finds himself bound for 1955 and face to face with his teenage parents -- again.',
    'genres': 'Adventure|Comedy|Family|Science Fiction',
    'title': 'Back to the Future Part II',
    'year': '1989'},
   'query': 'Movies similar to Find all Science Fiction Movies involving Time Travel.'},
  {'id': '49530',
   'document': "Movie: In Time\nYear: 2011\nGenres: Action, Thriller, Science Fiction\nOverview: In the not-too-distant future the aging gene has been switched off. To avoid overpopulation, time has become the currency and the way people pay for luxuries and necessities. The rich can live forever, while the rest try to negotiate for their immortality. A poor young man who comes into a fortune of time, though too late to help his mother from dying. He ends up on the run from a corrupt police force known as 'time keepers'.\n",
   'metadata': {'title': 'In Time',
    'genres': 'Action|Thriller|Science Fiction',
    'year': '2011',
    'overview': "In the not-too-distant future the aging gene has been switched off. To avoid overpopulation, time has become the currency and the way people pay for luxuries and necessities. The rich can live forever, while the rest try to negotiate for their immortality. A poor young man who comes into a fortune of time, though too late to help his mother from dying. He ends up on the run from a corrupt police force known as 'time keepers'."},
   'query': 'Plot description: Find all Science Fiction Movies involving Time Travel.'},
  {'id': '13811',
   'document': "Movie: Knowing\nYear: 2009\nGenres: Action, Adventure, Drama, Mystery, Science Fiction, Thriller\nOverview: A teacher opens a time capsule that has been dug up at his son's elementary school; in it are some chilling predictions -- some that have already occurred and others that are about to -- that lead him to believe his family plays a role in the events that are about to unfold.\n",
   'metadata': {'year': '2009',
    'genres': 'Action|Adventure|Drama|Mystery|Science Fiction|Thriller',
    'overview': "A teacher opens a time capsule that has been dug up at his son's elementary school; in it are some chilling predictions -- some that have already occurred and others that are about to -- that lead him to believe his family plays a role in the events that are about to unfold.",
    'title': 'Knowing'},
   'query': 'Movie themes and content about Find all Science Fiction Movies involving Time Travel.'},
  {'id': '8831',
   'document': 'Movie: Timecop\nYear: 1994\nGenres: Thriller, Science Fiction, Action, Crime\nOverview: An officer for a security agency that regulates time travel, must fend for his life against a shady politician who has a tie to his past.\n',
   'metadata': {'title': 'Timecop',
    'year': '1994',
    'genres': 'Thriller|Science Fiction|Action|Crime',
    'overview': 'An officer for a security agency that regulates time travel, must fend for his life against a shady politician who has a tie to his past.'},
   'query': 'For the identified science fiction movies about time travel, filter for those with strong character development.'},
  {'id': '13805',
   'document': 'Movie: Disaster Movie\nYear: 2008\nGenres: Action, Comedy\nOverview: In DISASTER MOVIE, the filmmaking team behind the hits "Scary Movie," "Date Movie," "Epic Movie" and "Meet The Spartans" this time puts its unique, inimitable stamp on one of the biggest and most bloated movie genres of all time -- the disaster film.\n',
   'metadata': {'year': '2008',
    'genres': 'Action|Comedy',
    'overview': 'In DISASTER MOVIE, the filmmaking team behind the hits "Scary Movie," "Date Movie," "Epic Movie" and "Meet The Spartans" this time puts its unique, inimitable stamp on one of the biggest and most bloated movie genres of all time -- the disaster film.',
    'title': 'Disaster Movie'},
   'query': 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '10683',
   'document': 'Movie: Happiness\nYear: 1998\nGenres: Comedy, Drama\nOverview: The lives of many individuals connected by the desire for happiness, often from sources usually considered dark or evil.\n',
   'metadata': {'genres': 'Comedy|Drama',
    'title': 'Happiness',
    'overview': 'The lives of many individuals connected by the desire for happiness, often from sources usually considered dark or evil.',
    'year': '1998'},
   'query': 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '12228',
   'document': 'Movie: Inside Deep Throat\nYear: 2005\nGenres: History, Documentary\nOverview: In 1972, a seemingly typical shoestring budget pornographic film was made in a Florida hotel, "Deep Throat," starring Linda Lovelace. This film would surpass the wildest expectation of everyone involved to become one of the most successful independent films of all time. It caught the public imagination which met the spirit of the times, even as the self appointed guardians of public morality struggled to suppress it, and created, for a brief moment, a possible future where sexuality in film had a bold artistic potential. This film covers the story of the making of this controversial film, its stunning success, its hysterical opposition along with its dark side of mob influence and allegations of the on set mistreatment of the film\'s star. In short, the combined events would redefine the popular appeal of pornography, even as more cynical developments would lead it down other paths.\n',
   'metadata': {'year': '2005',
    'genres': 'History|Documentary',
    'overview': 'In 1972, a seemingly typical shoestring budget pornographic film was made in a Florida hotel, "Deep Throat," starring Linda Lovelace. This film would surpass the wildest expectation of everyone involved to become one of the most successful independent films of all time. It caught the public imagination which met the spirit of the times, even as the self appointed guardians of public morality struggled to suppress it, and created, for a brief moment, a possible future where sexuality in film had a bold artistic potential. This film covers the story of the making of this controversial film, its stunning success, its hysterical opposition along with its dark side of mob influence and allegations of the on set mistreatment of the film\'s star. In short, the combined events would redefine the popular appeal of pornography, even as more cynical developments would lead it down other paths.',
    'title': 'Inside Deep Throat'},
   'query': 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '178862',
   'document': "Movie: Aroused\nYear: 2013\nGenres: Documentary\nOverview: Get up close and personal with 16 of the most successful women in the adult film industry as they shed their clothes for an intimate photo shoot with director Deborah Anderson. As questions are asked, personal stories about their lives are revealed, from why they chose the business of sex to how they got into it in the first place. These porn stars have always been discreet about their private lives in the past, yet Anderson has a way of opening up a dialog allowing them to share more than just their naked skin on screen. Their true inner vulnerability is touching, yet the characters they have created are confident and intoxicating. Once you hear their stories, you'll never look at them in the same way again.\n",
   'metadata': {'genres': 'Documentary',
    'overview': "Get up close and personal with 16 of the most successful women in the adult film industry as they shed their clothes for an intimate photo shoot with director Deborah Anderson. As questions are asked, personal stories about their lives are revealed, from why they chose the business of sex to how they got into it in the first place. These porn stars have always been discreet about their private lives in the past, yet Anderson has a way of opening up a dialog allowing them to share more than just their naked skin on screen. Their true inner vulnerability is touching, yet the characters they have created are confident and intoxicating. Once you hear their stories, you'll never look at them in the same way again.",
    'title': 'Aroused',
    'year': '2013'},
   'query': 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '76996',
   'document': 'Movie: Love and Other Catastrophes\nYear: 1996\nGenres: Comedy, Romance\nOverview: A day in the life of two film-school students trying to find love and another house-mate.\n',
   'metadata': {'genres': 'Comedy|Romance',
    'title': 'Love and Other Catastrophes',
    'year': '1996',
    'overview': 'A day in the life of two film-school students trying to find love and another house-mate.'},
   'query': 'Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '15624',
   'document': 'Movie: Conversations with Other Women\nYear: 2006\nGenres: Drama, Romance\nOverview: Reunited at a wedding after many years, former lovers again feel the pull of a mutual attraction neither is willing to admit. Escaping the reception for the privacy of a hotel room, the unnamed pair explore the choices of the past that led them to the present.\n',
   'metadata': {'title': 'Conversations with Other Women',
    'genres': 'Drama|Romance',
    'overview': 'Reunited at a wedding after many years, former lovers again feel the pull of a mutual attraction neither is willing to admit. Escaping the reception for the privacy of a hotel room, the unnamed pair explore the choices of the past that led them to the present.',
    'year': '2006'},
   'query': 'Movies similar to Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '15544',
   'document': 'Movie: Extreme Movie\nYear: 2008\nGenres: Comedy\nOverview: A sketch comedy movie about the joys and embarrassments of teen sex. But mostly the embarrassments.\n',
   'metadata': {'genres': 'Comedy',
    'overview': 'A sketch comedy movie about the joys and embarrassments of teen sex. But mostly the embarrassments.',
    'title': 'Extreme Movie',
    'year': '2008'},
   'query': 'Movies similar to Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '107985',
   'document': "Movie: The World's End\nYear: 2013\nGenres: Comedy, Action, Science Fiction\nOverview: Five friends who reunite in an attempt to top their epic pub crawl from 20 years earlier unwittingly become humankind's only hope for survival.\n",
   'metadata': {'genres': 'Comedy|Action|Science Fiction',
    'year': '2013',
    'overview': "Five friends who reunite in an attempt to top their epic pub crawl from 20 years earlier unwittingly become humankind's only hope for survival.",
    'title': "The World's End"},
   'query': 'Movies similar to Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '139998',
   'document': 'Movie: Supporting Characters\nYear: 2012\nGenres: Drama, Comedy\nOverview: Two New York film editors balance their personal relationships while reworking a movie in crisis.\n',
   'metadata': {'title': 'Supporting Characters',
    'genres': 'Drama|Comedy',
    'overview': 'Two New York film editors balance their personal relationships while reworking a movie in crisis.',
    'year': '2012'},
   'query': 'Plot description: Finally, from that filtered list of films, select only those also exhibiting emotional depth'},
  {'id': '17436',
   'document': "Movie: The Informers\nYear: 2008\nGenres: Drama\nOverview: A collection of intersecting short stories set in early 1980's Los Angeles, depicts a week in the lives of an assortment of socially alienated, mainly well-off characters who numb their sense of emptiness with casual sex, violence, and drugs.\n",
   'metadata': {'year': '2008',
    'overview': "A collection of intersecting short stories set in early 1980's Los Angeles, depicts a week in the lives of an assortment of socially alienated, mainly well-off characters who numb their sense of emptiness with casual sex, violence, and drugs.",
    'title': 'The Informers',
    'genres': 'Drama'},
   'query': 'Movie themes and content about Finally, from that filtered list of films, select only those also exhibiting emotional depth'}])